"""ajustes en modelos

Revision ID: ab42518a5ff9
Revises: e5f82e4c1975
Create Date: 2025-10-27 19:04:04.513254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab42518a5ff9'
down_revision = 'e5f82e4c1975'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
