"""crear tablas base

Revision ID: e24bdb0670cf
Revises: 
Create Date: 2025-10-27 18:10:44.753244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24bdb0670cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros',
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_index(op.f('ix_libros_isbn'), 'libros', ['isbn'], unique=False)
    op.create_table('socios',
    sa.Column('id_socio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_socio'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_socios_id_socio'), 'socios', ['id_socio'], unique=False)
    op.create_table('ejemplares',
    sa.Column('id_ejemplar', sa.Integer(), nullable=False),
    sa.Column('libro_isbn', sa.String(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['libro_isbn'], ['libros.isbn'], ),
    sa.PrimaryKeyConstraint('id_ejemplar')
    )
    op.create_index(op.f('ix_ejemplares_id_ejemplar'), 'ejemplares', ['id_ejemplar'], unique=False)
    op.create_table('prestamos',
    sa.Column('id_prestamo', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('ejemplar_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prestamo', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ejemplar_id'], ['ejemplares.id_ejemplar'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socios.id_socio'], ),
    sa.PrimaryKeyConstraint('id_prestamo')
    )
    op.create_index(op.f('ix_prestamos_id_prestamo'), 'prestamos', ['id_prestamo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prestamos_id_prestamo'), table_name='prestamos')
    op.drop_table('prestamos')
    op.drop_index(op.f('ix_ejemplares_id_ejemplar'), table_name='ejemplares')
    op.drop_table('ejemplares')
    op.drop_index(op.f('ix_socios_id_socio'), table_name='socios')
    op.drop_table('socios')
    op.drop_index(op.f('ix_libros_isbn'), table_name='libros')
    op.drop_table('libros')
    # ### end Alembic commands ###
