"""actualizar tablas

Revision ID: e5f82e4c1975
Revises: e24bdb0670cf
Create Date: 2025-10-27 18:56:16.364906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f82e4c1975'
down_revision = 'e24bdb0670cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
